tailscale:
  hostname: tailvoy-l7-test-tailvoy
  serviceMappings:
    web: [web]
  tags:
    - tag:docker
  serviceTags:
    - tag:docker-svc

listeners:
  web:
    port: 80
    protocol: http
    routes:
      - backend: backend:8080
